version: '3.7'

services:
  web:
    image: web
    restart: always
    container_name: web
    ports:
      - 8081:80
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf