version: '3.7'

services:
  mysql_db:
    image: mysql
    restart: always
    container_name: mysql_db
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - apps/api-server/.env
    volumes:
      - mysql_volume:/data/mysql
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
  api_server:
    image: api_server
    restart: always
    container_name: api_server
    ports:
      - 3000:3000
    build:
      context: apps/api-server/
    env_file:
      - apps/api-server/.env
    depends_on:
      - mysql_db
  web:
    image: web
    restart: always
    container_name: web
    ports:
      - 80:80
    build:
      context: apps/web/
    env_file:
      - apps/web/.env
    volumes:
      - ./apps/web/nginx/nginx.conf:/etc/nginx/nginx.conf
volumes:
  mysql_volume:
    driver: local
